### ISSUE TITLE
关于模型测试结果

### ISSUE THREAD

**Issue by cyy-1102** [ttengwang/PDVC#19]
您好，我用您的训练的模型测试，出现以下情况，请问您知道是什么原因吗？

/home/yy/anaconda3/envs/DVC1/bin/python /home/yy/桌面/PDVC/eval.py --eval_folder=anet_c3d_pdvc --eval_model_path=model-best.pth
{'eval_save_dir': 'save', 'eval_mode': 'eval', 'test_video_feature_folder': None, 'test_video_meta_data_csv_path': None, 'eval_folder': 'anet_c3d_pdvc', 'eval_model_path': 'model-best.pth', 'eval_tool_version': '2018', 'eval_caption_file': 'data/anet/captiondata/val_1.json', 'eval_proposal_type': 'gt', 'eval_transformer_input_type': 'queries', 'gpu_id': ['0'], 'eval_device': 'cuda'}
load info from save/anet_c3d_pdvc/info.json
load translator, total_vocab: %d 5747
load captioning file, %d captioning loaded 4917
/home/yy/anaconda3/envs/DVC1/lib/python3.7/site-packages/torch/nn/modules/rnn.py:61: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
all decoder layers share the same caption head
Loading model from save/anet_c3d_pdvc/model-best.pth
alpha: 1.0, temp: 2.0
loss: OrderedDict([('loss_ce', 0.19), ('loss_counter', 0.116), ('loss_bbox', 0.151), ('loss_giou', 0.302), ('loss_self_iou', 0.144), ('cardinality_error', 3.56), ('loss_ce_0', 0.18), ('loss_counter_0', 0.117), ('loss_bbox_0', 0.331), ('loss_giou_0', 0.503), ('loss_self_iou_0', 0.242), ('cardinality_error_0', 3.56), ('total_loss', 4.075)])
available video number 4917
PTBTokenizer tokenized 610661 tokens at 1464671.40 tokens per second.
PTBTokenizer tokenized 583002 tokens at 1426850.56 tokens per second.
Traceback (most recent call last):
  File "/home/yy/桌面/PDVC/eval.py", line 144, in <module>
    main(opt)
  File "/home/yy/桌面/PDVC/eval.py", line 109, in main
    logger, alpha=opt.ec_alpha, dvc_eval_version=opt.eval_tool_version, device=opt.eval_device, debug=False, skip_lang_eval=False)
  File "/home/yy/桌面/PDVC/eval_utils.py", line 224, in evaluate
    dvc_eval_version=dvc_eval_version
  File "/home/yy/桌面/PDVC/eval_utils.py", line 124, in eval_metrics
    dvc_score = eval_dvc(json_path=dvc_filename, reference=gt_filenames, version=dvc_eval_version)
  File "/home/yy/桌面/PDVC/densevid_eval3/eval_dvc.py", line 13, in eval_dvc
    score = eval_func(args)
  File "/home/yy/桌面/PDVC/densevid_eval3/evaluate2018.py", line 261, in main
    evaluator.evaluate()
  File "/home/yy/桌面/PDVC/densevid_eval3/evaluate2018.py", line 113, in evaluate
    scores = self.evaluate_tiou(tiou)
  File "/home/yy/桌面/PDVC/densevid_eval3/evaluate2018.py", line 237, in evaluate_tiou
    score, scores = scorer.compute_score(gts[vid_id], res[vid_id])
  File "/home/yy/桌面/PDVC/densevid_eval3/pycocoevalcap/meteor/meteor.py", line 37, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "/home/yy/桌面/PDVC/densevid_eval3/pycocoevalcap/meteor/meteor.py", line 57, in _stat
    self.meteor_p.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

**Comment by ttengwang** [comment]
@cyy-1102 Please refer to  https://github.com/tylin/coco-caption/issues/17#issuecomment-249883619

**Comment by cyy-1102** [comment]
> @cyy-1102 Please refer to [tylin/coco-caption#17 (comment)](https://github.com/tylin/coco-caption/issues/17#issuecomment-249883619)

thank you very much
