### ISSUE TITLE
Error when run make.sh

### ISSUE THREAD

**Issue by binzzheng** [ttengwang/PDVC#9]
```
running build
running build_py
running build_ext
building 'MultiScaleDeformableAttention' extension
Emitting ninja build file /home/binzheng/code/PDVC-main/pdvc/ops/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] /usr/bin/nvcc -DWITH_CUDA -I/home/binzheng/code/PDVC-main/pdvc/ops/src -I/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/include -I/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/include/TH -I/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/include/THC -I/home/binzheng/anaconda3/envs/PDVCC/include/python3.7m -c -c /home/binzheng/code/PDVC-main/pdvc/ops/src/cuda/ms_deform_attn_cuda.cu -o /home/binzheng/code/PDVC-main/pdvc/ops/build/temp.linux-x86_64-3.7/home/binzheng/code/PDVC-main/pdvc/ops/src/cuda/ms_deform_attn_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=MultiScaleDeformableAttention -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
FAILED: /home/binzheng/code/PDVC-main/pdvc/ops/build/temp.linux-x86_64-3.7/home/binzheng/code/PDVC-main/pdvc/ops/src/cuda/ms_deform_attn_cuda.o 
/usr/bin/nvcc -DWITH_CUDA -I/home/binzheng/code/PDVC-main/pdvc/ops/src -I/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/include -I/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/include/TH -I/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/include/THC -I/home/binzheng/anaconda3/envs/PDVCC/include/python3.7m -c -c /home/binzheng/code/PDVC-main/pdvc/ops/src/cuda/ms_deform_attn_cuda.cu -o /home/binzheng/code/PDVC-main/pdvc/ops/build/temp.linux-x86_64-3.7/home/binzheng/code/PDVC-main/pdvc/ops/src/cuda/ms_deform_attn_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=MultiScaleDeformableAttention -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
nvcc fatal   : Unsupported gpu architecture 'compute_75'
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1539, in _run_ninja_build
    env=env)
  File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 70, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 500, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1255, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```
This error message appeared when I run make.sh. How can I solve it? Thank you!

**Comment by cyy-1102** [comment]
> ```
> running build
> running build_py
> running build_ext
> building 'MultiScaleDeformableAttention' extension
> Emitting ninja build file /home/binzheng/code/PDVC-main/pdvc/ops/build/temp.linux-x86_64-3.7/build.ninja...
> Compiling objects...
> Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
> [1/1] /usr/bin/nvcc -DWITH_CUDA -I/home/binzheng/code/PDVC-main/pdvc/ops/src -I/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/include -I/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/include/TH -I/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/include/THC -I/home/binzheng/anaconda3/envs/PDVCC/include/python3.7m -c -c /home/binzheng/code/PDVC-main/pdvc/ops/src/cuda/ms_deform_attn_cuda.cu -o /home/binzheng/code/PDVC-main/pdvc/ops/build/temp.linux-x86_64-3.7/home/binzheng/code/PDVC-main/pdvc/ops/src/cuda/ms_deform_attn_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=MultiScaleDeformableAttention -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
> FAILED: /home/binzheng/code/PDVC-main/pdvc/ops/build/temp.linux-x86_64-3.7/home/binzheng/code/PDVC-main/pdvc/ops/src/cuda/ms_deform_attn_cuda.o 
> /usr/bin/nvcc -DWITH_CUDA -I/home/binzheng/code/PDVC-main/pdvc/ops/src -I/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/include -I/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/include/TH -I/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/include/THC -I/home/binzheng/anaconda3/envs/PDVCC/include/python3.7m -c -c /home/binzheng/code/PDVC-main/pdvc/ops/src/cuda/ms_deform_attn_cuda.cu -o /home/binzheng/code/PDVC-main/pdvc/ops/build/temp.linux-x86_64-3.7/home/binzheng/code/PDVC-main/pdvc/ops/src/cuda/ms_deform_attn_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=MultiScaleDeformableAttention -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
> nvcc fatal   : Unsupported gpu architecture 'compute_75'
> ninja: build stopped: subcommand failed.
> Traceback (most recent call last):
>   File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1539, in _run_ninja_build
>     env=env)
>   File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/subprocess.py", line 512, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "setup.py", line 70, in <module>
>     cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
>   File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
>     return distutils.core.setup(**attrs)
>   File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/dist.py", line 966, in run_commands
>     self.run_command(cmd)
>   File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/command/build.py", line 135, in run
>     self.run_command(cmd_name)
>   File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
>     _build_ext.run(self)
>   File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/command/build_ext.py", line 340, in run
>     self.build_extensions()
>   File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
>     build_ext.build_extensions(self)
>   File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
>     self._build_extensions_serial()
>   File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
>     self.build_extension(ext)
>   File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
>     _build_ext.build_extension(self, ext)
>   File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
>     depends=ext.depends)
>   File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 500, in unix_wrap_ninja_compile
>     with_cuda=with_cuda)
>   File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1255, in _write_ninja_file_and_compile_objects
>     error_prefix='Error compiling objects for extension')
>   File "/home/binzheng/anaconda3/envs/PDVCC/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
>     raise RuntimeError(message) from e
> RuntimeError: Error compiling objects for extension
> ```
> 
> This error message appeared when I run make.sh. How can I solve it? Thank you!

you can try "conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=9.2 -c pytorch", if not, you can reference “https://blog.csdn.net/Cuzyan/article/details/121465098?spm=1001.2014.3001.5501”
